test:
  access_key_id: AKIAJDWWG5F6T22MPELA
  secret_access_key: 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
development:
  access_key_id: AKIAJDWWG5F6T22MPELA
  secret_access_key: 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
production:
  access_key_id: ENV['S3_KEY'],
  secret_access_key: ENV['S3_SECRET']